src/gallery/models.py
from src import db


class Work(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(256), unique=True, nullable=False)
    created = db.Column(db.String(256), nullable=False)
    description = db.Column(db.Text)
    images = db.relationship(
        'Image', backref='work', cascade='all, delete-orphan'
    )

    def __repr__(self):
        return f'<Work(id={self.id}, title={self.title}, created={self.created})>'


class Image(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(256), unique=True, nullable=False)
    description = db.Column(db.Text)
    work_id = db.Column(db.Integer, db.ForeignKey('work.id'))

    def __repr__(self):
        return f'<Image(id={self.id}, title={self.title}, work_id={self.work_id})>'

src/gallery/__init__.py
from flask import Blueprint

bp = Blueprint('gallery', __name__, template_folder='templates')

from src.gallery import create
from src.gallery import update
from src.gallery import views

src/gallery/views.py
import os

from flask import redirect
from flask import render_template
from flask import url_for
from werkzeug.exceptions import abort

from src import db
from src.auth.views import login_required
from src.gallery import bp
from src.gallery.models import Image
from src.gallery.models import Work
from src.lib.funcs import get_upload_path


@bp.route('/')
def index():
    return render_template('index.html')


@bp.route('/<int:id>')
def detail(id):
    return render_template(
        'detail_work.html',
        work=Work.query.get_or_404(id),
        images=Image.query.filter_by(work_id=id).order_by(Image.id).all()
    )


@bp.route('/<int:id>/delete', methods=('POST',))
@login_required
def delete(id):
    work = Work.query.get(id)
    db.session.delete(work)
    db.session.commit()

    for i in work.images:
        os.remove(get_upload_path() / i.title)
    return redirect(url_for('gallery.index'))


@bp.route('/remove_photo/<int:id>', methods=('POST',))
def remove_photo(id):
    image = Image.query.get(id)
    work_id = image.work.id
    db.session.delete(image)
    db.session.commit()
    os.remove(get_upload_path() / image.title)
    return redirect(url_for('gallery.WorkImageList', id=work_id))

src/gallery/templates/add_image.html
{% extends 'base.html' %}
{% block title %}Add image to "{{ work.title }}" {% endblock %}
{% block content %}
	<section class="background-light dark flex--view-priority">
		<div class="container">
			<div class="pad-top64px pad-btm64px">
				<form method="post" enctype="multipart/form-data">
					<ul class="flex flex--column flex--gap36px none-list-style">
						<li class="auth-text"><label for="image_description">Description</label></li>
						<li>
							<textarea class="auth-create-textarea" name="image_description" id="image_description">{{ request.form['image_description'] }}</textarea>
						</li>
						<li class="flex flex--center fontsize16px flex--gap12px">
							<input id="image" name="image" type="file">
						</li>
						<li><input class="fontsize16px auth-btn auth-btn-primary" type="submit" value="Save"></li>
					</ul>
				</form>
			</div>
			<div class="flex flex--gap24px">
				<a class="btn-link" href="{{ url_for('gallery.WorkImageList', id=work.id) }}">&#x2190;&nbsp;Images of {{ work.title }}</a>
				<a class="btn-link" href="{{ url_for('gallery.UpdateWork', id=work.id) }}">Update {{ work.title }}</a>
			</div>
		</div>
	</section>
{% endblock %}

src/gallery/templates/create.html
{% extends 'base.html' %}
{% block title %}Add work {% endblock %}
{% block content %}
	<section class="background-light dark flex--view-priority">
		<div class="container">
			<div class="pad-top64px pad-btm64px">
				<form method="post" enctype="multipart/form-data">
					<ul class="flex flex--column flex--gap36px none-list-style">
						<li class="auth-text"><label for="title">Title</label></li>
						<li><input name="title" id="title" value="{{ request.form['title'] }}" required></li>
						<li class="auth-text"><label for="description">Description</label></li>
						<li>
							<textarea class="auth-create-textarea" name="description" id="description">{{ request.form['description'] }}</textarea>
						</li>

						<hr/>
						<li class="flex flex--column fontsize16px flex--gap24px">
							<label for="image_description">Image description</label>
							<textarea id="image_description" class="auth-create-textarea" name="image_description">{{ request.form['image_description'] }}</textarea>
							<input id="image" name="image" type="file">
						</li>
						<li><input class="fontsize16px auth-btn auth-btn-primary" type="submit" value="Save"></li>
					</ul>
				</form>
			</div>
		</div>
	</section>
{% endblock %}

src/gallery/templates/detail_image.html
{% extends 'base.html' %}

{% block content %}
	<section class="background-light dark flex--view-priority">
		<div class="container">
			<div class="flex flex--column flex--gap36px pad-top64px pad-btm64px">
				<form method="post" enctype="multipart/form-data">
					<ul class="flex flex--column flex--gap36px none-list-style">
						<img src="{{ url_for('static', filename='images/' + image.title) }}" alt="Not Found"/>
						<li class="flex flex--center fontsize16px flex--gap12px">
							<input id="image" name="image" type="file">
							<label for="image_description">Description</label>
							<textarea id="image_description" class="auth-create-textarea" name="image_description">{{ request.form['image_description'] or image.description }}</textarea>
						</li>
						<li><input class="fontsize16px auth-btn auth-btn-primary" type="submit" value="Save"></li>
					</ul>
				</form>
			<div class="flex flex--gap24px">
				<a class="btn-link" href="{{ url_for('gallery.WorkImageList', id=image.work_id) }}">&#x2190;&nbsp;Images</a>
				<a class="btn-link" href="{{ url_for('gallery.detail', id=image.work_id) }}">{{ image.work.title }}</a>
			</div>
			</div>
		</div>
	</section>
{% endblock %}

src/gallery/templates/detail_work.html
{% extends 'base.html' %}
{% block title %}"{{ work.title }}" {% endblock %}
{% block content %}
	<section class="background-light dark flex--view-priority">
		<div class="container">
			<div class="flex flex--column detail-flex-gap detail-inner">
				<p class="detail-title letterspacing1-5px qoc">{{ work.title }}</p>
				{% if g.user.username == 'admin' %}
					<p class="fontsize24px">created: {{ work.created }}</p>
					<div class="flex flex--center flex--gap24px">
						<a class="btn-link" href="{{ url_for('gallery.UpdateWork', id=work.id) }}">Edit</a>
						<form action="{{ url_for('gallery.delete', id=work.id) }}" method="post">
							<input class="fontsize16px auth-btn auth-btn-danger" type="submit" value="Delete work" onclick="return confirm('Are you sure?');"/>
						</form>
					</div>
				{% endif %}
				<p class="fontsize24px">{{ work.description }}</p>
				{% if images %}
					{% for i in images %}
						<img src="{{ url_for('static', filename='images/' + i.title) }}">
						{% if i.description %}
							<p class="fontsize24px">{{ i.description }}</p>
						{% endif %}
					{% endfor %}
				{% else %}
					<p>Not Found</p>
				{% endif %}
			</div>
		</div>
	</section>
{% endblock %}

src/gallery/templates/images_list.html
{% extends 'base.html' %}
{% block title %}"{{ work.title }}" images {% endblock %}
{% block content %}
	<section class="background-light dark flex--view-priority">
		<div class="container">
			<div class="flex flex--column flex--gap36px pad-top64px pad-btm64px">
				<div class="flex flex--gap24px">
					<a class="btn-link" href="{{ url_for('gallery.UpdateWork', id=work.id) }}">&#x2190;&nbsp;Update work</a>
					<a class="btn-link fontsize16px" href="{{ url_for('gallery.AddWorkImage', id=work.id) }}">Add an image</a>
					<a class="btn-link fontsize16px" href="{{ url_for('gallery.detail', id=work.id) }}">{{ work.title }} detail</a>
				</div>
				{% if images %}
					{% for i in images %}
						<div class="flex flex--column flex--gap12px">
							<p class="fontsize16px">{{ i.title }}</p>
							<img class="img-width20" src="{{ url_for('static', filename='images/' + i.title) }}"/>
							{% if i.description %}
								<p class="fontsize16px">{{ i.description }}</p>
							{% endif %}
						</div>
						<div class="flex flex--center flex--gap24px">
							<div>
								<a class="btn-link" href="{{ url_for('gallery.DetailImage', work_id=work.id, image_id=i.id) }}">Detail</a>
							</div>
							<form action="{{ url_for('gallery.remove_photo', id=i.id) }}" method="post">
								<input class="fontsize16px auth-btn auth-btn-danger" type="submit" value="Remove photo" onclick="return confirm('Are you sure?');">
							</form>
						</div>
						{% if not loop.last %}
							<hr/>
						{% endif %}
					{% endfor %}
				{% else %}
					<p class="fontsize16px">No images yet</p>
				{% endif %}
			</div>
		</div>
	</section>
{% endblock %}

src/gallery/templates/index.html
{% extends 'base.html' %}

{% block content %}
	<section class="light carousel">
		<div class="container">
			<div class="carousel--inner">
				<p class="carousel--heading-primary">Прості та вигідні рішення для бізнесу</p>
				<p class="carousel--desc">Ознайомтеся з нашими пропозиціями та послугами, зробіть свій бізнес стильним та впізнаваним. Ми гарантуємо унікальний дизайн, який сподобається вам та вашим клієнтам, у короткий термін та за приємну ціну.</p>
				<a class="btn-link" href="#offer">Переглянути пропозиції</a>
			</div>
		</div>
	</section>

	<section class="background-dark light pad-top64px pad-btm64px">
		<div class="container flex statistics-flex">
			<div>
				<p class="statistics-count qoc">0286</p>
				<p class="fontsize24px statistics-info">Виконаних замовлень</p>
			</div>
			<div>
				<p class="statistics-count qoc">0152</p>
				<p class="fontsize24px statistics-info">Унікальних дизайнів</p>
			</div>
			<div>
				<p class="statistics-count qoc">0068</p>
				<p class="fontsize24px statistics-info">Задоволених клієнтів</p>
			</div>
		</div>
	</section>

	<section class="background-light dark" id="cooldesign">
		<div class="container">
			<p class="cooldesign-title qoc">РОБИМО КРУТИЙ ДИЗАЙН ДЛЯ НАШИХ КЛІЄНТІВ</p>
			<p class="cooldesign-info">Ми - команда Sheikhs, наша робота - це про ваш бізнес та його обличчя. Щодня ми приймаємо десятки замовлень від клієнтів, консультуємо та допомагаємо у розвитку їх справ. Робимо логотипи, вивіски, поліграфічні матеріали, навігацію, візуалізації та концепти для ваших соцмереж, торгових точок, офісів та робочих місць.</p>
			<div class="flex flex--center cooldesign-inner">
				<div>
					<img class="cooldesign-img" src="{{ url_for('static', filename='images/01.png') }}" alt="Not Found">
					<p class="cooldesign-p">Створюємо унікальну айдентику, та повний бренд-пакет для вашого бізнесу</p>
				</div>
				<div>
					<img class="cooldesign-img" src="{{ url_for('static', filename='images/02.png') }}" alt="Not Found">
					<p class="cooldesign-p">Дослуховуємось до усіх побажань та вибудовуємо роботу у вашому режимі</p>
				</div>
				<div>
					<img class="cooldesign-img" src="{{ url_for('static', filename='images/03.png') }}" alt="Not Found">
					<p class="cooldesign-p">Візуалізуємо усю роботу, виконуємо замовлення по поліграфії та віддаємо готовий продукт</p>
				</div>
			</div>
		</div>
	</section>

	<section class="background-dark light" id="portfolio">
		<div class="container portfolio-inner">
			<p class="portfolio-title qoc">НАШЕ ПОРТФОЛІО</p>
			<div class="grid portfolio-grid">
				<div class="portfolio--div-img">
					<a href="{{ url_for('gallery.detail', id=13) }}">
						<img class="img-width100" src="{{ url_for('static', filename='images/' + '1_Leggitop_title_image.svg') }}">
					</a>
				</div>
				<div class="portfolio--div-img">
					<a href="{{ url_for('gallery.detail', id=14) }}">
						<img class="img-width100" src="{{ url_for('static', filename='images/' + '2_Pidshypnyk_group_title_image.svg') }}">
					</a>
				</div>
				<div class="portfolio--div-img">
					<a href="{{ url_for('gallery.detail', id=15) }}">
						<img class="img-width100" src="{{ url_for('static', filename='images/' + '3_d0cplay_title_image.svg') }}">
					</a>
				</div>
				<div class="portfolio--div-img">
					<a href="{{ url_for('gallery.detail', id=16) }}">
						<img class="img-width100" src="{{ url_for('static', filename='images/' + '4_MSI_title_image.svg') }}">
					</a>
				</div>
				<div class="portfolio--div-img">
					<a href="{{ url_for('gallery.detail', id=17) }}">
						<img class="img-width100" src="{{ url_for('static', filename='images/' + '5_Bearing_store_title_image.svg') }}">
					</a>
				</div>
				<div class="portfolio--div-img">
					<a href="{{ url_for('gallery.detail', id=18) }}">
						<img class="img-width100" src="{{ url_for('static', filename='images/' + '6_Purple_lama_title_image.svg') }}">
					</a>
				</div>
			</div>
		</div>
	</section>

	<section class="background-light" id="offer">
		<div class="offer-cont container">
			<p class="offer-title dark qoc">ЩО МИ ПРОПОНУЄМО?</p>
			<div class="light offer-flex">
				<div class="flex flex--column background-dark">
					<p class="offer-type qoc">БАЗОВИЙ ПАКЕТ</p>
					<p class="offer-price qoc">3000<span>&#8372;</span></p>
					<ul class="flex flex--column offer-list">
						<li class="offer-info"><img class="offer-icon" src="{{ url_for('static', filename='images/checkmark.svg') }}" alt="Not Found"/><span>Два варіанти логотипу з доопрацюванням одного обраного</span></li>
						<li class="offer-info"><img class="offer-icon" src="{{ url_for('static', filename='images/checkmark.svg') }}" alt="Not Found"/><span>Пакет підготованих файлів для друку та web-використання</span></li>
						<li class="offer-info"><img class="offer-icon" src="{{ url_for('static', filename='images/crossmark.svg') }}" alt="Not Found"/><span class="offer-text">Презентація з прикладами застосування логотипу та візуалізаціями</span></li>
						<li class="offer-info"><img class="offer-icon" src="{{ url_for('static', filename='images/crossmark.svg') }}" alt="Not Found"/><span class="offer-text">Розробка коротких версій логотипу (іконки для соцмереж, сайтів тощо)</span></li>
						<li class="offer-info"><img class="offer-icon" src="{{ url_for('static', filename='images/crossmark.svg') }}" alt="Not Found"/><span class="offer-text">Створення корпоративної палітри кольорів</span></li>
						<li class="offer-info"><img class="offer-icon" src="{{ url_for('static', filename='images/crossmark.svg') }}" alt="Not Found"/><span class="offer-text">Підготовка фірмових текстур для соцмереж та трьох макетів поліграфії (візитівки, флаєри, фірмові бланки тощо)</span></li>
					</ul>
				</div>
				<div class="background-dark">
					<p class="offer-type qoc">СТАНДАРТНИЙ ПАКЕТ</p>
					<p class="offer-price qoc">4000<span>&#8372;</span></p>
					<ul class="flex flex--column offer-list">
						<li class="offer-info"><img class="offer-icon" src="{{ url_for('static', filename='images/checkmark.svg') }}" alt="Not Found"/><span>Три варіанти логотипу з доопрацюванням одного обраного</span></li>
						<li class="offer-info"><img class="offer-icon" src="{{ url_for('static', filename='images/checkmark.svg') }}" alt="Not Found"/><span>Пакет підготованих файлів для друку та web-використання</span></li>
						<li class="offer-info"><img class="offer-icon" src="{{ url_for('static', filename='images/checkmark.svg') }}" alt="Not Found"/><span>Презентація з прикладами застосування логотипу та візуалізаціями</span></li>
						<li class="offer-info"><img class="offer-icon" src="{{ url_for('static', filename='images/checkmark.svg') }}" alt="Not Found"/><span>Розробка коротких версій логотипу (іконки для соцмереж, сайтів тощо)</span></li>
						<li class="offer-info"><img class="offer-icon" src="{{ url_for('static', filename='images/crossmark.svg') }}" alt="Not Found"/><span class="offer-text">Створення корпоративної палітри кольорів</span></li>
						<li class="offer-info"><img class="offer-icon" src="{{ url_for('static', filename='images/crossmark.svg') }}" alt="Not Found"/><span class="offer-text">Підготовка фірмових текстур для соцмереж та трьох макетів поліграфії (візитівки, флаєри, фірмові бланки тощо)</span></li>
					</ul>
				</div>
				<div class="background-dark">
					<p class="offer-type qoc">РОЗШИРЕНИЙ ПАКЕТ</p>
					<p class="offer-price qoc">5000<span>&#8372;</span></p>
					<ul class="flex flex--column offer-list">
						<li class="offer-info"><img class="offer-icon" src="{{ url_for('static', filename='images/checkmark.svg') }}" alt="Not Found"/><span>Чотири варіанти логотипу з доопрацюванням одного обраного</span></li>
						<li class="offer-info"><img class="offer-icon" src="{{ url_for('static', filename='images/checkmark.svg') }}" alt="Not Found"/><span>Пакет підготованих файлів для друку та web-використання</span></li>
						<li class="offer-info"><img class="offer-icon" src="{{ url_for('static', filename='images/checkmark.svg') }}" alt="Not Found"/><span>Презентація з прикладами застосування логотипу та візуалізаціями</span></li>
						<li class="offer-info"><img class="offer-icon" src="{{ url_for('static', filename='images/checkmark.svg') }}" alt="Not Found"/><span>Розробка коротких версій логотипу (іконки для соцмереж, сайтів тощо)</span></li>
						<li class="offer-info"><img class="offer-icon" src="{{ url_for('static', filename='images/checkmark.svg') }}" alt="Not Found"/><span>Створення корпоративної палітри кольорів</span></li>
						<li class="offer-info"><img class="offer-icon" src="{{ url_for('static', filename='images/checkmark.svg') }}" alt="Not Found"/><span>Підготовка фірмових текстур для соцмереж та трьох макетів поліграфії (візитівки, флаєри, фірмові бланки тощо)</span></li>
					</ul>
				</div>
			</div>
		</div>
	</section>
{% endblock %}

src/gallery/templates/update.html
{% extends 'base.html' %}
{% block title %}Edit "{{ work.title }}" {% endblock %}
{% block content %}
	<section class="background-light dark flex--view-priority">
		<div class="container">
			<div class="flex flex--column flex--gap36px pad-top64px pad-btm64px">
				<form method="post" enctype="multipart/form-data">
					<ul class="flex flex--column flex--gap36px none-list-style">
						<li class="auth-text"><label for="title">Title</label></li>
						<li>
							<input name="title" id="title" value="{{ request.form['title'] or work.title }}" required/>
						</li>
						<li class="auth-text"><label for="description">Description</label></li>
						<li>
							<textarea class="auth-create-textarea" name="description" id="description">{{ request.form['description'] or work.description }}</textarea>
						</li>
						<li>
							<input class="fontsize16px auth-btn auth-btn-primary" type="submit" value="Save"/>
						</li>
					</ul>
				</form>
				<div class="flex flex--gap24px">
					<a class="btn-link" href="{{ url_for('gallery.detail', id=work.id) }}">&#x2190;&nbsp;Detail</a>
					<a class="btn-link" href="{{ url_for('gallery.WorkImageList', id=work.id) }}">Images</a>
				</div>
			</div>
		</div>
	</section>
{% endblock %}